### ISSUE TITLE
Architekturális tervezés

### ISSUE THREAD

**Issue by aklakina** [MysticMazeEducators/.github#4]
[Doc](https://docs.google.com/document/d/1GTv_dlfl4zy5qWqVaSZ-0cV_lKCpe7kK/edit)

- 2.2.1
- 2.2.4
- 2.4.1
- 2.4.2

**Comment by aklakina** [comment]
24/02/24: 14:00 - 18:00—4 óra

**Comment by regensburgerervin** [comment]
Munkaóra naplózva
