### ISSUE TITLE
Funkciók

### ISSUE THREAD

**Issue by Rizsa01** [MysticMazeEducators/.github#6]
[Doc](https://docs.google.com/document/d/1GTv_dlfl4zy5qWqVaSZ-0cV_lKCpe7kK/edit)

- 2.1.2 Szakterület
- 2.2.2 Funkciók
- 2.2.3 Felhasználók
- 2.2.5 Feltételezések, kapcsolatok

**Comment by Rizsa01** [comment]
24/02/23: 19:20 - 20:50: 1.5 óra

**Comment by Rizsa01** [comment]
24/02/24: 21:50 - 22:20: 0.5 óra

**Comment by regensburgerervin** [comment]
Munkaóra naplózva
