### ISSUE TITLE
Bevezetés és Szótár

### ISSUE THREAD

**Issue by P1nter** [MysticMazeEducators/.github#8]
[Doc](https://docs.google.com/document/d/1GTv_dlfl4zy5qWqVaSZ-0cV_lKCpe7kK/edit)

- 2.1.1
- 2.1.3
- 2.1.4
- 2.1.5
- 2.6

**Comment by P1nter** [comment]
Szótár -- 22:30-0:30 -- 2 óra

**Comment by P1nter** [comment]
Definíciók, 2.3.4 -- 21:30-22:30 -- 1 óra

**Comment by regensburgerervin** [comment]
Munkaóra naplózva
